### ISSUE TITLE
origin error for the forked repo when multiple github accounts exist on the laptop

### ISSUE THREAD

**Issue by BatmansKtichen** [pwn2winctf/2017#4]
When multiple github accounts are setup on the laptop (via ssh config file), while we can change the settings.json for the cloned repo's github_ssh_url, but when we fork a repo, it does not honor this ssh url, thus causing trouble when commiting after fork, to resolve this issue, I have added a line in

line 46 of [subrepo.py](https://github.com/pwn2winctf/2017/blob/master/nizkctf/subrepo.py#L46)

```python
if fork:                                                                
    cls.git(['remote', 'set-url', 'origin', repohost.get_ssh_url(forked_project)])
```

which correctly resets the remote origin url for the forked repo honoring the setting in settings.json

**Comment by thotypous** [comment]
Patch applied. Thank you very much for the contribution!
